// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk887571938/appengine/go_appengine/goroot`
const TheVersion = `1.6.4 (appengine-1.9.54)`
const Goexperiment = ``
const StackGuardMultiplier = 1

